---
title: "Raleigh NIBRS Police Data Set Analyses"
output:
  html_document:
    code_folding: hide
    toc: true
runtime: shiny
---
<style>
  .main-container {max-width: 65%;}
  .row {overflow: auto;}
</style>
<hr/>
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Import and Prepare Dataset
```{r message=FALSE, warning=FALSE}
# Import required packages
library('tidyverse')
library('shiny')
library('DT')


# Import data
policeFile = './data/Raleigh_Police_Incidents_(NIBRS).csv'
police = read_csv(policeFile)

# Drop unneeded features
police = police %>% select(-GlobalID, -case_number, -agency, -OBJECTID, -X, -Y, -city, -reported_block_address, -city_of_incident)

# Replace NA crime types with 'Other Crimes' and change capitalization of non-NA crime types
police = police %>% mutate(
  crime_type = ifelse(
    is.na(crime_type),
    'Other Crimes',
    ifelse(
      crime_type == 'CRIMES AGAINST PERSONS',
      'Crimes Against Persons',
      ifelse(
        crime_type == 'CRIMES AGAINST PROPERTY',
        'Crimes Against Property',
        ifelse(
          crime_type == 'CRIMES AGAINST SOCIETY',
          'Crimes Against Society',
          'Other Crimes'
        )
      )
    )
  )
)

# Rename crime_description column
police = police %>% rename(Crime = crime_description)

# Filter observations to only include crimes with known district
police = police %>% filter(district != 'UNK')

# Count number of crimes in different districts to get a list of districts
districts = police %>% count(district)

# Count individual crimes to get a list of crimes sorted alphabetically
indivCrimes = police %>% count(Crime) %>% arrange(Crime)

# Create a factor for the days of the week to aid in sorting
police$reported_dayofwk = factor(police$reported_dayofwk, levels = c('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'))
```

# Visualize Trends Between Districts for Given Year and Type of Crime
```{r echo=FALSE, message=FALSE, warning=FALSE}
ui = fluidPage(
  sidebarLayout(
    sidebarPanel(
      selectInput(
        'crimeType',
        label = 'Type of Crime:',
        choices = c('Crimes Against Persons', 'Crimes Against Property', 'Crimes Against Society', 'Other Crimes')
      ),
      selectInput(
        'xAxis',
        label = 'Time Frame:',
        choices = c('Day of Week', 'Month'),
        selected = 'Day of Week'
      ),
      sliderInput(
        'year',
        label = 'Year:',
        min = 2014,
        max = 2021,
        value = 2021,
        step = 1,
        sep = ''
      )
    ),
    mainPanel(
      plotOutput('mainPlot')
    )
  ),
  DT::dataTableOutput('crimeDescTable')
)

server = function(input, output, session) {
  dataObj = reactive({
    it = police %>% filter(crime_type == input$crimeType, reported_year == input$year)
    
    return(it)
  })
  
  listener = reactive({
    list(input$crimeType, input$xAxis, input$year)
  })
  
  re = eventReactive(
    listener(),
    {
      if (input$xAxis == 'Day of Week') {
        ggplot(data = dataObj()) + geom_bar(mapping = aes(x = reported_dayofwk, fill = district)) + xlab('Day of Week') + ylab('Number of Crimes Reported') + scale_fill_discrete(name = 'District') + ggtitle(paste(input$crimeType, 'in', input$year, 'by Day of Week'))
      }
      else if (input$xAxis == 'Month') {
        ggplot(data = dataObj()) + geom_bar(mapping = aes(x = factor(reported_month), fill = district)) + xlab('Month') + ylab('Number of Crimes Reported') + scale_fill_discrete(name = 'District') + ggtitle(paste(input$crimeType, 'in', input$year, 'by Month'))
      }
    }
  )
  
  output$mainPlot = renderPlot({
    re()
  })
  
  crimeDataObj = reactive({
    it = dataObj() %>% count(Crime) %>% arrange(-n) %>% rename('Number Reported' = n)
    
    return(it)
  })
  
  output$crimeDescTable = DT::renderDataTable({
    crimeDataObj()
  })
}

shinyApp(
  ui,
  server,
  options = list(
    height = '870'
  )
)
```

# Visualize Trends Between Districts for Given Crime
*Note: The data for 2014 (before June) and 2021 (from the end of March onward) are incomplete so exercise caution when looking at yearly and monthly trends.*
```{r echo=FALSE, message=FALSE, warning=FALSE}
ui2 = fluidPage(
  sidebarLayout(
    mainPanel(
      plotOutput(outputId = 'crimeHist')
    ),
    sidebarPanel(
      textInput(
      'searchCrime',
      'Search:'
      ),
      uiOutput('chooseCrime'),
      selectInput(
        'xAxis',
        label = 'Time Frame:',
        choices = c('Day of Week', 'Month', 'Year'),
        selected = 'Year'
      )
    )
  )
)

server2 = function(input, output, session) {
  dataObj = reactive({
    if (length(input$chooseCrime) == 0) {return(NA)}
    
    it = police %>% filter(Crime == input$chooseCrime)
    return(it)
  })
  
  filteredCrimes = reactive({
    idxs = mapply(
      grepl,
      input$searchCrime,
      list(indivCrimes$Crime),
      ignore.case = TRUE,
      SIMPLIFY = FALSE
    )
    indivCrimes$Crime[idxs[[1]]]
  })
  
  observeEvent(
    input$searchCrime,
    {
      updateSelectInput(
        session,
        'chooseCrime',
        choices = filteredCrimes()
      )
    }
  )
  
  output$chooseCrime = renderUI({
    selectInput(
      'chooseCrime',
      'Crime:',
      choices = filteredCrimes(),
      width = 500
    )
  })
  
  listener = reactive({
    list(input$chooseCrime, input$xAxis)
  })
  
  re = eventReactive(
    listener(),
    {
      if (input$xAxis == 'Day of Week') {
        ggplot(data = dataObj()) + geom_bar(mapping = aes(x = reported_dayofwk, fill = district)) + xlab('Day of Week') + ylab('Number of Crimes Reported') + scale_fill_discrete(name = 'District') + ggtitle(paste(input$chooseCrime, 'by Day of Week'))
      }
      else if (input$xAxis == 'Month') {
        ggplot(data = dataObj()) + geom_bar(mapping = aes(x = factor(reported_month), fill = district)) + xlab('Month') + ylab('Number of Crimes Reported') + scale_fill_discrete(name = 'District') + ggtitle(paste(input$chooseCrime, 'by Month'))
      }
      else if (input$xAxis == 'Year') {
        ggplot(data = dataObj()) + geom_bar(mapping = aes(fill = district, x = factor(reported_year))) + xlab('Year') + ylab('Number of Crimes Reported') + scale_fill_discrete(name = 'District') + ggtitle(paste('Reports of', input$chooseCrime, 'by Year'))
      }
    }
  )
  
  output$crimeHist = renderPlot({
    re()
  })
}

shinyApp(
  ui2,
  server2,
  options = list(
    height = 600
  )
)
```
